language: ruby
rvm:
  - "2.2.2"
before_script: bundle exec rake db:setup
before_install: gem update bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
