language: ruby
rvm:
  - "2.2.4"
  - "2.3.0"
before_script: bundle exec rake db:setup
before_install: gem update bundler
cache: bundler
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
sudo: false