language: ruby
rvm:
  - "2.1.2"
before_script: rake db:setup
before_script: bundle exec rake db:setup
notifications:
  email:
    recipients:
    - jasnow@hotmail.com
    on_success: change
    on_failure: always
